### ISSUE TITLE
Problem with List object

### ISSUE THREAD

**Issue by Tartinovitch** [deadc0de6/catcli#1]
Hi,

When I run 'catcli index ...' , I have an AttributeError: 'list' object has no attribute 'splitlines'

+-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.4.5
Traceback (most recent call last):
  File "/Users/tt/.pyenv/versions/3.6.0/bin/catcli", line 11, in <module>
    sys.exit(main())
  File "/Users/tt/.pyenv/versions/3.6.0/lib/python3.6/site-packages/catcli/__init__.py", line 13, in main
    if catcli.catcli.main():
  File "/Users/tt/.pyenv/versions/3.6.0/lib/python3.6/site-packages/catcli/catcli.py", line 204, in main
    cmd_index(args, noder, catalog, top)
  File "/Users/tt/.pyenv/versions/3.6.0/lib/python3.6/site-packages/catcli/catcli.py", line 80, in cmd_index
    attr = noder.clean_storage_attr(args['--meta'])
  File "/Users/tt/.pyenv/versions/3.6.0/lib/python3.6/site-packages/catcli/noder.py", line 57, in clean_storage_attr
    return ', '.join(attr.splitlines())
AttributeError: 'list' object has no attribute 'splitlines'

What i need to do ?
Thanks

**Comment by deadc0de6** [comment]
Thanks for reporting this! It was indeed a bug, it should be fixed in the new version (v0.4.6)

**Comment by Tartinovitch** [comment]
Problem solved. Thanks for your work
