### ISSUE TITLE
Noder PY Issue

### ISSUE THREAD

**Issue by pflores429** [deadc0de6/catcli#21]
Seeing the following issue when I go to run tree:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\catcli.exe\__main__.py", line 7, in <module>
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\__init__.py", line 13, in main
    if catcli.catcli.main():
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\catcli.py", line 292, in main
    cmd_tree(args, noder, top)
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\catcli.py", line 191, in cmd_tree
    noder.print_tree(node, fmt=fmt, header=hdr)
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\noder.py", line 434, in print_tree
    self._to_csv(node, with_header=header)
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\noder.py", line 442, in _to_csv
    self._node_to_csv(node)
  File "C:\Users\pflores\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\catcli\noder.py", line 318, in _node_to_csv
    out.append(utils.epoch_to_str(node.maccess))
AttributeError: 'AnyNode' object has no attribute 'maccess

**Comment by deadc0de6** [comment]
I don't use Windows but the bug fix in version 0.8.3 should fix your issue: <https://pypi.org/project/catcli/>
Let me know if you have other issues on Windows.

**Comment by deadc0de6** [comment]
I spoke too soon and introduced a regression bug in 0.8.3. Fixed in 0.8.5 available on [pypi](https://pypi.org/project/catcli/), sorry for that!

**Comment by pflores429** [comment]
updated and issue appears to be resolved.  But I see new "fields"/"columns" in the CSV format ( nbfiles, free_space, total_space, and meta) that are not included (as of yet) in the readme.  If interested I can provide windows examples of the commands.

**Comment by deadc0de6** [comment]
You're absolutely right, I'll update the README.
