### ISSUE TITLE
clicat v0.5.1 on Debian: AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by de-ramon** [deadc0de6/catcli#4]
Hi,
just installed clicat by
```
pip3 install catcli
Collecting catcli
  Downloading https://files.pythonhosted.org/packages/f1/06/0253f58a67a143c5bdbeffa8c36574e9c16f4ab0703b42682b02cab3cba4/catcli-0.5.1-py3-none-any.whl
Collecting docopt (from catcli)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting anytree (from catcli)
  Downloading https://files.pythonhosted.org/packages/b9/cd/abd10f53ba136c77dd6c68aa96d9e6881b9713c4778fd8e854ff5d9787ba/anytree-2.4.3.tar.gz
Collecting psutil (from catcli)
  Downloading https://files.pythonhosted.org/packages/7d/9a/1e93d41708f8ed2b564395edfa3389f0fd6d567597401c2e5e2775118d8b/psutil-5.4.7.tar.gz (420kB)
    100% |████████████████████████████████| 430kB 2.2MB/s 
Collecting six>=1.9.0 (from anytree->catcli)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: docopt, anytree, psutil
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /home/ralf/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Running setup.py bdist_wheel for anytree ... done
  Stored in directory: /home/ralf/.cache/pip/wheels/ea/2f/04/b50f9b3761fb3c3c9c3b9ed01b2680c7ee99030f82fde1062b
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/ralf/.cache/pip/wheels/e2/9d/ea/1913d16f19bb927c32197308dec69cd8d10b61be8f7e265524
Successfully built docopt anytree psutil
Installing collected packages: docopt, six, anytree, psutil, catcli
Successfully installed anytree-2.4.3 catcli-0.5.1 docopt-0.6.2 psutil-5.4.7 six-1.11.0
```
and tried to index:
```
catcli index --meta='my test directory' -u tmptest /var/log
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.5.1

Traceback (most recent call last):
  File "/home/ralf/.local/bin/catcli", line 11, in <module>
    sys.exit(main())
  File "/home/ralf/.local/lib/python3.5/site-packages/catcli/__init__.py", line 13, in main
    if catcli.catcli.main():
  File "/home/ralf/.local/lib/python3.5/site-packages/catcli/catcli.py", line 231, in main
    cmd_index(args, noder, catalog, top, debug=args['--verbose'])
  File "/home/ralf/.local/lib/python3.5/site-packages/catcli/catcli.py", line 84, in cmd_index
    attr = noder.format_storage_attr(args['--meta'].split(','))
AttributeError: 'list' object has no attribute 'split'
```

What i need to do ?
Thx for your tool!,

Ralf

**Comment by deadc0de6** [comment]
Thanks for reporting this.
It was indeed a bug. I fixed it and released a new version (that is also directly available on pypi).
Let me know if you have other issues

**Comment by de-ramon** [comment]
Hi,

works like a charm :)

thx,

ramon
